
defaults:
  loot_homepage: 'new_page_with_logic_filters'
  loot_details_page: 'old_page'

development:
  loot_homepage: '2c2c3486-a10b-49ce-a305-ebe744746002'
  loot_details_page: 'a3e1781e-ca03-4cc9-a2a1-138d8534f10b'

test:
  loot_homepage: 'bloop'
  loot_details_page: 'bloop'

staging:
  loot_homepage: '90dff472-58c0-4ff3-a791-8f2220aa2a31'
  loot_details_page: '778449df-cc54-4ae2-bdfb-89a9cc125462'

production:
  loot_homepage: 'f29a677b-9c6a-45f5-9912-e877bd872b87'
  loot_details_page: '92a07f83-b6e0-4990-98a4-98b36f001b79'