
defaults:
  loot_campaign_sort: 'most_sales'
  test_experiment: 'variant1'


test:
  test_experiment: 'c4030a09-cddd-4aa3-aa31-abba462b96fc'

development:
  loot_campaign_sort: 'a9ba2bc3-a9f6-4060-853f-97419246ca2f'